import {
  allInferredCapabilities,
  type CapabilityMap,
  type Coverage,
  type Finding,
  type RuntimeIntrospection,
  type ScanResult,
  type ScanTarget,
  type Severity,
} from '@mcp-trust/core';

// ---------------------------------------------------------------------------
// Self-contained HTML report. No external resources (inline CSS, no fonts/CDN),
// so it renders offline and can be served as a static artifact. EVERY
// interpolated string — including trusted dictionary text — is HTML-escaped, so
// an untrusted tool name / file path / redacted snippet can never inject markup.
// Secrets are already redacted upstream (redact()); we do not re-derive them.
// ---------------------------------------------------------------------------

/** HTML-escape text for element/attribute content. Applied to ALL interpolated
 * values without exception — the single defense against markup injection. */
function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function targetLabel(t: ScanTarget): string {
  switch (t.type) {
    case 'github':
      return `github:${t.owner}/${t.repo}${t.path ? `/${t.path}` : ''}`;
    case 'npm':
      return `npm:${t.packageName}${t.version ? `@${t.version}` : ''}`;
    case 'local':
    case 'config':
      return `${t.type}:${t.path}`;
    default:
      return t.type;
  }
}

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

/** CSS accent color per decision — kept low-saturation and theme-neutral. */
const DECISION_CLASS: Record<ScanResult['score']['decision'], string> = {
  BLOCK: 'decision-block',
  NEEDS_REVIEW: 'decision-review',
  APPROVE_WITH_RESTRICTIONS: 'decision-restrict',
  APPROVE: 'decision-approve',
};

export function renderHtml(result: ScanResult): string {
  const { score } = result;
  const title = `MCP Trust Report: ${targetLabel(result.target)}`;
  const body: string[] = [];

  body.push(`<header class="report-head ${DECISION_CLASS[score.decision]}">`);
  body.push(`<h1>${esc(title)}</h1>`);
  body.push('<div class="badges">');
  body.push(badge('Decision', score.decision));
  body.push(badge('Risk', score.risk.toUpperCase()));
  body.push(badge('Score', `${score.overall}/100`));
  body.push(badge('Confidence', `${Math.round(score.confidence * 100)}%`));
  body.push('</div>');
  if (result.resolvedRef) {
    body.push(`<p class="ref">Resolved ref: <code>${esc(result.resolvedRef)}</code></p>`);
  }
  body.push('</header>');

  body.push(section('Executive Summary', `<p>${esc(executiveSummary(result))}</p>`));

  if (result.limitations && result.limitations.length > 0) {
    body.push(
      `<section class="limitations"><h2>⚠️ Limitations</h2>\n${list(result.limitations.map((l) => esc(l)))}\n</section>`,
    );
  }

  body.push(
    section(
      'Decision Reasons',
      list(score.decisionReason.map((r) => esc(r))),
    ),
  );

  body.push(section('Coverage', coverageTable(result.coverage)));

  if (result.runtimeIntrospection) {
    body.push(section('Runtime Introspection', runtimeIntrospectionTable(result.runtimeIntrospection)));
  }

  if (result.capabilityMap) {
    body.push(section('Capability Map', capabilitySection(result.capabilityMap)));
  }

  body.push(section('Subscores', subscoresTable(score.subscores)));

  body.push(section(`Findings (${result.findings.length})`, findingsSection(result.findings)));

  body.push(
    section(
      'Recommended Policy',
      result.recommendedPolicy.length ? list(result.recommendedPolicy.map((p) => esc(p))) : '<p><em>None.</em></p>',
    ),
  );

  body.push(
    section('Disclaimer', `<blockquote>${esc(result.disclaimer)}</blockquote>`),
  );
  body.push(
    `<footer class="report-foot">Generated by ${esc(result.scanner.name)} ${esc(result.scanner.version)} at ${esc(result.generatedAt)}.</footer>`,
  );

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>${STYLE}</style>
</head>
<body>
<main class="report">
${body.join('\n')}
</main>
</body>
</html>
`;
}

function badge(label: string, value: string): string {
  return `<span class="badge"><span class="badge-label">${esc(label)}</span><span class="badge-value">${esc(value)}</span></span>`;
}

function section(heading: string, inner: string): string {
  return `<section><h2>${esc(heading)}</h2>\n${inner}\n</section>`;
}

function list(items: string[]): string {
  if (items.length === 0) return '<p><em>None.</em></p>';
  // Items are pre-escaped by callers.
  return `<ul>${items.map((i) => `<li>${i}</li>`).join('')}</ul>`;
}

function executiveSummary(result: ScanResult): string {
  switch (result.score.decision) {
    case 'BLOCK':
      return 'This MCP server should not be connected to developer workstations or production agents without remediation and sandboxing.';
    case 'NEEDS_REVIEW':
      return 'This MCP server requires human security review before use; notable risks were detected.';
    case 'APPROVE_WITH_RESTRICTIONS':
      return 'This MCP server may be used with restrictions (sandboxing, least privilege, scoped access).';
    default:
      return 'No significant risks were detected in the available evidence. Standard review still applies.';
  }
}

/** Render a 2-column key/value table. Keys and values are both escaped. */
function kvTable(headers: [string, string], rows: [string, string][]): string {
  const head = `<tr><th>${esc(headers[0])}</th><th>${esc(headers[1])}</th></tr>`;
  const trs = rows.map(([k, v]) => `<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join('');
  return `<table><thead>${head}</thead><tbody>${trs}</tbody></table>`;
}

function coverageTable(c: Coverage): string {
  return kvTable(['Check', 'State'], Object.entries(c).map(([k, v]) => [k, String(v)]));
}

function runtimeIntrospectionTable(r: RuntimeIntrospection): string {
  const rows: [string, string][] = [
    ['Status', r.status],
    ['Transport', r.transport],
    ['Client', r.client],
    ['Tools discovered', String(r.toolsDiscovered)],
    ['Resources discovered', String(r.resourcesDiscovered)],
    ['Prompts discovered', String(r.promptsDiscovered)],
  ];
  if (r.sandbox) {
    rows.push(
      ['Sandbox', `${r.sandbox.kind} (image ${r.sandbox.image})`],
      ['Sandbox network', r.sandbox.network],
      ['Read-only root FS', r.sandbox.readOnlyRootFilesystem ? 'yes' : 'no'],
    );
  } else {
    rows.push(['Sandbox', 'none (host process)']);
  }
  return kvTable(['Field', 'Value'], rows);
}

function subscoresTable(subscores: ScanResult['score']['subscores']): string {
  const rows: [string, string][] = Object.entries(subscores).map(([k, v]) => [
    k,
    v == null ? 'not assessed' : String(v),
  ]);
  return kvTable(['Subscore', 'Value'], rows);
}

function capabilitySection(map: CapabilityMap): string {
  const out: string[] = [`<p class="muted">Source: ${esc(map.source)}</p>`];
  if (map.tools.length > 0) {
    const rows = map.tools
      .map((t) => {
        const caps =
          t.inferredCapabilities.map((c) => `${c.category} (${Math.round(c.confidence * 100)}%)`).join(', ') || '—';
        const max = t.inferredCapabilities.length
          ? `${Math.round(Math.max(...t.inferredCapabilities.map((c) => c.confidence)) * 100)}%`
          : '—';
        return `<tr><td>${esc(t.name)}</td><td>${esc(caps)}</td><td>${esc(max)}</td></tr>`;
      })
      .join('');
    out.push(
      `<table><thead><tr><th>Tool</th><th>Inferred capability</th><th>Confidence</th></tr></thead><tbody>${rows}</tbody></table>`,
    );
  } else {
    const agg = allInferredCapabilities(map);
    if (agg.length === 0) {
      out.push(
        '<p><em>No tools discovered (no runtime introspection); capabilities inferred statically where possible.</em></p>',
      );
    } else {
      out.push(
        kvTable(
          ['Inferred capability', 'Confidence'],
          agg.map((c) => [c.category, `${Math.round(c.confidence * 100)}%`]),
        ),
      );
    }
  }
  return out.join('\n');
}

function findingsSection(findings: Finding[]): string {
  if (findings.length === 0) return '<p><em>No findings.</em></p>';
  const out: string[] = [];
  for (const sev of SEVERITY_ORDER) {
    const group = findings.filter((f) => f.severity === sev);
    if (group.length === 0) continue;
    out.push(`<h3 class="sev sev-${sev}">${esc(sev.toUpperCase())} (${group.length})</h3>`);
    for (const f of group) out.push(renderFinding(f));
  }
  return out.join('\n');
}

function renderFinding(f: Finding): string {
  const ev = f.evidence[0];
  const loc = ev ? `${ev.file ?? ev.source}${ev.line != null ? `:${ev.line}` : ''}` : '—';
  const parts: string[] = [];
  parts.push('<article class="finding">');
  parts.push(`<h4>${esc(f.ruleId)}: ${esc(f.title)}</h4>`);
  parts.push(
    `<p class="finding-meta"><strong>Severity:</strong> ${esc(f.severity)} · <strong>Confidence:</strong> ${Math.round(
      f.confidence * 100,
    )}% · <strong>Category:</strong> ${esc(f.category)}</p>`,
  );
  parts.push(`<p>${esc(f.description)}</p>`);
  parts.push(`<p><strong>Evidence:</strong> <code>${esc(loc)}</code></p>`);
  if (ev?.snippet) parts.push(`<pre class="snippet"><code>${esc(ev.snippet)}</code></pre>`);
  parts.push(`<p><strong>Impact:</strong> ${esc(f.impact)}</p>`);
  parts.push(`<p><strong>Remediation:</strong> ${esc(f.remediation)}</p>`);
  parts.push('</article>');
  return parts.join('\n');
}

const STYLE = `
:root{color-scheme:light dark;--bg:#ffffff;--fg:#1a1d21;--muted:#5c636e;--border:#e2e5ea;--card:#f7f8fa;--code:#eef0f3;--accent:#3b6fb0;--sev-critical:#b42318;--sev-high:#c4571b;--sev-medium:#9a7400;--sev-low:#3b6fb0;--sev-info:#5c636e}
@media (prefers-color-scheme:dark){:root{--bg:#14171a;--fg:#e6e9ee;--muted:#9aa3af;--border:#2a2f36;--card:#1b1f24;--code:#22272d;--accent:#7aa7dd;--sev-critical:#f0776a;--sev-high:#e6975a;--sev-medium:#d9bd63;--sev-low:#7aa7dd;--sev-info:#9aa3af}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.report{max-width:860px;margin:0 auto;padding:2rem 1.25rem 4rem}
h1{font-size:1.5rem;margin:0 0 .75rem}
h2{font-size:1.15rem;margin:2rem 0 .6rem;padding-bottom:.3rem;border-bottom:1px solid var(--border)}
h3{font-size:1rem;margin:1.4rem 0 .5rem}
h4{font-size:.98rem;margin:0 0 .4rem}
.report-head{border-left:5px solid var(--accent);padding:1rem 1.1rem;background:var(--card);border-radius:8px}
.decision-block{--accent:var(--sev-critical)}
.decision-review{--accent:var(--sev-high)}
.decision-restrict{--accent:var(--sev-medium)}
.decision-approve{--accent:#2e8b57}
.badges{display:flex;flex-wrap:wrap;gap:.5rem;margin-top:.5rem}
.badge{display:inline-flex;flex-direction:column;background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:.35rem .6rem;min-width:80px}
.badge-label{font-size:.7rem;text-transform:uppercase;letter-spacing:.04em;color:var(--muted)}
.badge-value{font-weight:600;font-size:1.05rem}
.ref{color:var(--muted);font-size:.85rem;margin:.6rem 0 0}
.muted,.report-foot{color:var(--muted)}
p{margin:.5rem 0}
ul{margin:.4rem 0;padding-left:1.3rem}
li{margin:.2rem 0}
table{border-collapse:collapse;width:100%;font-size:.9rem;margin:.4rem 0;display:block;overflow-x:auto}
th,td{border:1px solid var(--border);padding:.4rem .55rem;text-align:left;vertical-align:top}
th{background:var(--card);font-weight:600}
code{background:var(--code);padding:.1rem .35rem;border-radius:4px;font:.85em ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;word-break:break-word}
pre.snippet{background:var(--code);padding:.6rem .75rem;border-radius:6px;overflow-x:auto}
pre.snippet code{background:none;padding:0}
blockquote{margin:.4rem 0;padding:.5rem .9rem;border-left:3px solid var(--border);color:var(--muted)}
.finding{border:1px solid var(--border);border-radius:8px;padding:.85rem 1rem;margin:.7rem 0;background:var(--card)}
.finding-meta{font-size:.85rem;color:var(--muted)}
.sev{padding-left:.55rem;border-left:4px solid var(--border)}
.sev-critical{border-color:var(--sev-critical);color:var(--sev-critical)}
.sev-high{border-color:var(--sev-high);color:var(--sev-high)}
.sev-medium{border-color:var(--sev-medium);color:var(--sev-medium)}
.sev-low{border-color:var(--sev-low);color:var(--sev-low)}
.sev-info{border-color:var(--sev-info);color:var(--sev-info)}
.report-foot{margin-top:2.5rem;padding-top:1rem;border-top:1px solid var(--border);font-size:.82rem}
.limitations{background:color-mix(in srgb,var(--sev-medium) 12%,var(--bg));border:1px solid var(--sev-medium);border-radius:8px;padding:.4rem 1rem 1rem}
.limitations h2{border-bottom:none;color:var(--sev-medium)}
`;
