import {
  allInferredCapabilities,
  type CapabilityMap,
  type Coverage,
  type Finding,
  type RuntimeIntrospection,
  type ScanResult,
  type ScanTarget,
} from '@mcp-trust/core';

function targetLabel(t: ScanTarget): string {
  switch (t.type) {
    case 'github':
      return `github:${t.owner}/${t.repo}${t.path ? `/${t.path}` : ''}`;
    case 'npm':
      return `npm:${t.packageName}${t.version ? `@${t.version}` : ''}`;
    case 'local':
    case 'config':
      return `${t.type}:${t.path}`;
    default:
      return t.type;
  }
}

const SEVERITY_HEADERS: Finding['severity'][] = ['critical', 'high', 'medium', 'low', 'info'];

/** Neutralize a value going into a Markdown table cell: escape `|`, angle
 * brackets (raw HTML) and backticks, and drop newlines. Untrusted tool names /
 * file paths cannot then break the table or inject HTML/markup. */
function mdCell(s: string): string {
  return s
    .replace(/[\r\n]+/g, ' ')
    .replace(/\|/g, '\\|')
    .replace(/`/g, '‘')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/** Neutralize a value going inside an inline `code span`: no backticks (would
 * close the span), no newlines. */
function mdInline(s: string): string {
  return s.replace(/[\r\n]+/g, ' ').replace(/`/g, '‘');
}

export function renderMarkdown(result: ScanResult): string {
  const { score } = result;
  const lines: string[] = [];
  lines.push(`# MCP Trust Report: ${targetLabel(result.target)}`);
  lines.push('');
  lines.push(`**Decision:** ${result.score.decision}  `);
  lines.push(`**Risk:** ${score.risk.toUpperCase()}  `);
  lines.push(`**Score:** ${score.overall}/100  `);
  lines.push(`**Confidence:** ${Math.round(score.confidence * 100)}%`);
  if (result.resolvedRef) lines.push(`\n_Resolved ref: \`${result.resolvedRef}\`_`);
  lines.push('');

  lines.push('## Executive Summary');
  lines.push(executiveSummary(result));
  lines.push('');

  if (result.limitations && result.limitations.length > 0) {
    lines.push('## ⚠️ Limitations');
    for (const l of result.limitations) lines.push(`- ${mdInline(l)}`);
    lines.push('');
  }

  lines.push('## Decision Reasons');
  for (const r of score.decisionReason) lines.push(`- ${r}`);
  lines.push('');

  lines.push('## Coverage');
  lines.push(coverageTable(result.coverage));
  lines.push('');

  if (result.runtimeIntrospection) {
    lines.push('## Runtime Introspection');
    lines.push(runtimeIntrospectionSection(result.runtimeIntrospection));
    lines.push('');
  }

  if (result.capabilityMap) {
    lines.push('## Capability Map');
    lines.push(capabilitySection(result.capabilityMap));
    lines.push('');
  }

  lines.push('## Subscores');
  lines.push('| Subscore | Value |');
  lines.push('|---|---|');
  for (const [k, v] of Object.entries(score.subscores)) {
    lines.push(`| ${k} | ${v == null ? '_not assessed_' : v} |`);
  }
  lines.push('');

  lines.push(`## Findings (${result.findings.length})`);
  if (result.findings.length === 0) {
    lines.push('_No findings._');
  } else {
    for (const sev of SEVERITY_HEADERS) {
      const group = result.findings.filter((f) => f.severity === sev);
      if (group.length === 0) continue;
      lines.push(`### ${sev.toUpperCase()} (${group.length})`);
      for (const f of group) lines.push(renderFinding(f));
    }
  }
  lines.push('');

  lines.push('## Recommended Policy');
  for (const p of result.recommendedPolicy) lines.push(`- ${p}`);
  lines.push('');

  lines.push('## Disclaimer');
  lines.push(`> ${result.disclaimer}`);
  lines.push('');
  lines.push(`_Generated by ${result.scanner.name} ${result.scanner.version} at ${result.generatedAt}._`);
  lines.push('');
  return lines.join('\n');
}

function executiveSummary(result: ScanResult): string {
  const d = result.score.decision;
  if (d === 'BLOCK')
    return 'The scanner found **high-confidence capability evidence in the server’s runtime code** (e.g. command execution). Review the flagged findings below before connecting this server to an agent. **A BLOCK is a "review required", not proof the server is malicious** — the evidence may be legitimate by design (see Decision Reasons).';
  if (d === 'NEEDS_REVIEW')
    return 'The scanner found **notable capabilities or patterns worth a human look** (listed under Decision Reasons and Findings). **This is not a rejection** — read the specific findings and decide based on your threat model. Many are expected for what the server does (e.g. network access for a fetch server).';
  if (d === 'APPROVE_WITH_RESTRICTIONS')
    return 'This MCP server looks usable **with restrictions** (sandboxing, least privilege, scoped access). Review the findings and apply the recommended policy.';
  return 'No significant risks were detected in the available evidence. **This is not a safety guarantee** — standard review still applies, and see Coverage/Limitations for what was and wasn’t assessed.';
}

function runtimeIntrospectionSection(r: RuntimeIntrospection): string {
  const rows: string[] = [
    '| Field | Value |',
    '|---|---|',
    `| Status | ${r.status} |`,
    `| Transport | ${r.transport} |`,
    `| Client | ${r.client} |`,
    `| Tools discovered | ${r.toolsDiscovered} |`,
    `| Resources discovered | ${r.resourcesDiscovered} |`,
    `| Prompts discovered | ${r.promptsDiscovered} |`,
  ];
  if (r.sandbox) {
    rows.push(
      `| Sandbox | ${r.sandbox.kind} (image \`${r.sandbox.image}\`) |`,
      `| Sandbox network | ${r.sandbox.network} |`,
      `| Read-only root FS | ${r.sandbox.readOnlyRootFilesystem ? 'yes' : 'no'} |`,
    );
  } else {
    rows.push('| Sandbox | none (host process) |');
  }
  return rows.join('\n');
}

function coverageTable(c: Coverage): string {
  const rows = Object.entries(c).map(([k, v]) => `| ${k} | ${v} |`);
  return ['| Check | State |', '|---|---|', ...rows].join('\n');
}

function capabilitySection(map: CapabilityMap): string {
  const out: string[] = [`_Source: ${map.source}_`, ''];
  if (map.tools.length > 0) {
    out.push('| Tool | Inferred capability | Confidence |', '|---|---|---|');
    for (const t of map.tools) {
      const caps = t.inferredCapabilities.map((c) => `${c.category} (${Math.round(c.confidence * 100)}%)`).join(', ') || '—';
      out.push(`| ${mdCell(t.name)} | ${caps} | ${t.inferredCapabilities.length ? Math.round(Math.max(...t.inferredCapabilities.map((c) => c.confidence)) * 100) + '%' : '—'} |`);
    }
  } else {
    const agg = allInferredCapabilities(map);
    if (agg.length === 0) {
      out.push('_No tools discovered (no runtime introspection); capabilities inferred statically where possible._');
    } else {
      out.push('| Inferred capability | Confidence |', '|---|---|');
      for (const c of agg) out.push(`| ${c.category} | ${Math.round(c.confidence * 100)}% |`);
    }
  }
  return out.join('\n');
}

function renderFinding(f: Finding): string {
  const ev = f.evidence[0];
  const loc = ev ? `\`${mdInline(ev.file ?? ev.source)}${ev.line != null ? `:${ev.line}` : ''}\`` : '—';
  const parts = [
    `#### ${f.ruleId}: ${f.title}`,
    `**Severity:** ${f.severity}  **Confidence:** ${Math.round(f.confidence * 100)}%  **Category:** ${f.category}`,
    '',
    f.description,
    '',
    `**Evidence:** ${loc}`,
  ];
  if (ev?.snippet) parts.push('', '```', ev.snippet.replace(/```/g, "'''"), '```');
  parts.push('', `**Impact:** ${f.impact}`, '', `**Remediation:** ${f.remediation}`, '');
  return parts.join('\n');
}
