import { sanitizeUntrustedText, SEVERITY_ORDER, type Finding, type ScanResult, type ScanTarget } from '@mcp-trust/core';

// ---------------------------------------------------------------------------
// Compact PR-comment body (TZ §11.2). Not the full report — a decision line,
// risk, detected MCP configs and the top findings, with a pointer to the full
// artifact. Posted by the GitHub Action. Untrusted strings (tool/file names,
// config paths) are neutralized before entering Markdown.
// ---------------------------------------------------------------------------

const MARKER = '<!-- mcp-trust-report -->';

/** Stable marker so the Action can find-and-update its own comment instead of
 * posting a new one on every push. */
export const PR_COMMENT_MARKER = MARKER;

function targetLabel(t: ScanTarget): string {
  switch (t.type) {
    case 'github':
      return `github:${t.owner}/${t.repo}${t.path ? `/${t.path}` : ''}`;
    case 'npm':
      return `npm:${t.packageName}${t.version ? `@${t.version}` : ''}`;
    case 'local':
    case 'config':
      return `${t.type}:${t.path}`;
    default:
      return t.type;
  }
}

/** Neutralize an untrusted value for an inline `code span`: strip control/ANSI,
 * drop backticks (would close the span). */
function inlineCode(s: string): string {
  return (sanitizeUntrustedText(s, 200) ?? '').replace(/`/g, "'");
}

const DECISION_EMOJI: Record<string, string> = {
  APPROVE: '✅',
  APPROVE_WITH_RESTRICTIONS: '🟡',
  NEEDS_REVIEW: '🟠',
  BLOCK: '⛔',
};

/** Render the compact PR-comment Markdown. `reportUrl` (optional) links to the
 * uploaded full report artifact. The leading HTML marker lets the Action locate
 * and update its previous comment. */
export function renderPrComment(result: ScanResult, reportUrl?: string): string {
  const { score } = result;
  const emoji = DECISION_EMOJI[score.decision] ?? '';
  const lines: string[] = [MARKER, '## MCP Trust Scan Result', ''];
  lines.push(`**Target:** \`${inlineCode(targetLabel(result.target))}\``);
  lines.push('');
  lines.push(`Decision: **${score.decision}** ${emoji}  `);
  lines.push(`Risk: **${score.risk.toUpperCase()}**  `);
  lines.push(`Score: **${score.overall}/100**  ·  Confidence: **${Math.round(score.confidence * 100)}%**`);
  lines.push('');

  // Distinct config files that produced this scan's evidence.
  const configFiles = [
    ...new Set(
      result.findings
        .flatMap((f) => f.evidence)
        .filter((e) => e.source?.startsWith('config') && typeof e.file === 'string')
        .map((e) => e.file as string),
    ),
  ];
  if (configFiles.length > 0) {
    lines.push(`MCP configs detected: ${configFiles.map((c) => `\`${inlineCode(c)}\``).join(', ')}`);
    lines.push('');
  }

  const total = result.findings.length;
  if (total === 0) {
    lines.push('_No findings in the available evidence._');
  } else {
    const counts = countBySeverity(result.findings);
    lines.push(`**Findings (${total}):** ${counts}`);
    lines.push('');
    lines.push('Top findings:');
    const top = [...result.findings]
      .sort((a, b) => SEVERITY_ORDER[b.severity] - SEVERITY_ORDER[a.severity])
      .slice(0, 5);
    for (const f of top) {
      lines.push(`- \`${inlineCode(f.ruleId)}\` **[${f.severity}]** ${inlineCode(f.title)}`);
    }
  }
  lines.push('');
  if (reportUrl) lines.push(`[View full report](${encodeURI(reportUrl)})`);
  lines.push('');
  lines.push(`> ${sanitizeUntrustedText(result.disclaimer, 400) ?? ''}`);
  lines.push('');
  lines.push(`_Generated by ${result.scanner.name} ${result.scanner.version}._`);
  lines.push('');
  return lines.join('\n');
}

function countBySeverity(findings: Finding[]): string {
  const order: Finding['severity'][] = ['critical', 'high', 'medium', 'low', 'info'];
  const parts: string[] = [];
  for (const sev of order) {
    const n = findings.filter((f) => f.severity === sev).length;
    if (n > 0) parts.push(`${n} ${sev}`);
  }
  return parts.join(' · ') || 'none';
}
